### ISSUE TITLE
create a new app that contains amqbroker and fabric8mq

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-ipaas#101]
At the moment you have to run the two apps but they should be bundled into one template to avoid confusion

**Comment by rawlingsj** [comment]
relates to https://github.com/fabric8io/fabric8-ipaas/issues/100

**Comment by KurtStam** [comment]
https://github.com/fabric8io/fabric8-ipaas/pull/186.  Did you mean adding a package that contains both? Or did you mean replacing the existing two apps with one that contains both?
