### ISSUE TITLE
Adjust the d-m-p so it does not use latest in docker image from

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-ipaas#125]
Noticed that amqbroker will build using a latest image. I think the pom.xml files for ipaas needs to be looked at and do what we have done in the quickstarts to ensure we use a tagged version of the base image.

**Comment by KurtStam** [comment]
We need to add a version number like:

<docker.from>fabric8/java-jboss-openjdk8-jdk:1.0.10</docker.from>
taken from:
https://github.com/fabric8io/ipaas-quickstarts/blob/master/quickstart/java/fatjar/pom.xml#L45
