### ISSUE TITLE
Dependency issue over elasticsearch

### ISSUE THREAD

**Issue by tdcox** [fabric8io/fabric8-ipaas#147]
Apiman has a dependency upon elasticsearch 2.2.54 which clashes with version 2.2.95 deployed with Logging.

Deploying Apiman breaks both applications.

**Comment by KurtStam** [comment]
Yeah Apiman has not (yet) been updated to handle elastic search 2.x (the ES search API are not compatible unfortunately). We are now deploying ES 1.6 with apiman. The service is names elasticsearch-1. Please close if this works for you.

**Comment by KurtStam** [comment]
Please reopen if this is still an issue
