### ISSUE TITLE
[apiman] How to Invoke API does not provide valid endpoint

### ISSUE THREAD

**Issue by jpechane** [fabric8io/fabric8-ipaas#167]
If I go to Client App APIs and click on How to Invoke button I get an invalid URL
``null/gateway/myorg/elasticsearch-v1-masters/1.0?apikey=ccbe8114-444b-408d-ba4c-7d2d0ccb1e06``
Se the null at the beginning of URL

**Comment by jimmidyson** [comment]
@KurtStam Any ideas?

**Comment by KurtStam** [comment]
@jpechane Can you check the setting of your gateway endpoint (in the admin/gateways section of the UI)? It looks like it got lost.

**Comment by jpechane** [comment]
Gateway is there and the test is passing

**Comment by jpechane** [comment]
This disappeared after restart - I'm closing now
