### ISSUE TITLE
[apiman] Client App APIs - buttons Download as JSON/XML do not work

### ISSUE THREAD

**Issue by jpechane** [fabric8io/fabric8-ipaas#168]
By clicking on aforementioned buttons I get

```
HTTP ERROR: 401

Problem accessing /apiman/downloads/25818e73-9611-461f-9bc6-689c57278c7c. Reason:

    No BearerToken
```

**Comment by KurtStam** [comment]
Same explanation as https://github.com/fabric8io/fabric8-ipaas/issues/169

**Comment by jpechane** [comment]
Gateway is there and the test is passing

**Comment by jpechane** [comment]
https://github.com/fabric8io/fabric8-ipaas/issues/167 disappeared after restart but this one is stil present so probably diffeent root cause

**Comment by EricWittmann** [comment]
I think the problem with this one is that the /downloads part of the manager API is supposed to be unprotected (no auth required).  All the resources within /downloads are temporary (single-click download links).  So the web.xml should be configured such that authentication does *not* apply to /downloads.

Might be a problem with the micro-service config or with the ipaas impl.  I can have a look at some point.

**Comment by KurtStam** [comment]
Fixed by allowing anonymous access for this resource
