### ISSUE TITLE
[apiman] Clicking on endpoint type of services in API catalog leads to internal DNS names

### ISSUE THREAD

**Issue by jpechane** [fabric8io/fabric8-ipaas#169]
If I click on Endpoint Type icon in browser I get an URL with k8s internal DNS names.
An example ``http://apiman.jpechane.svc.cluster.local:7070/apiman/swagger.json``.

The same issue is probably root cuase for error when clicking on Definition for a service in the same page and after that button Download on *API Definition* page

**Comment by KurtStam** [comment]
Correct, that link should really be using the route. We've added fields for this now.

- The definitionLink should always be using the route
- The serviceEnd point should use the route if not yet imported, or else link to the management end endpoint.

https://issues.jboss.org/browse/APIMAN-915

This will be available after apiman-1.2.2 gets released.
