### ISSUE TITLE
[apiman] API Catalog should hide apiman and support services by default

### ISSUE THREAD

**Issue by jpechane** [fabric8io/fabric8-ipaas#170]
When a Service Import is to happen the list also suggests apiman, gateway, elasticsearch services that are probably not to be exposed. We thus propose
* annotate such services witch a special annotation
* provide a checkbox at API Catalog page that will be by default unchecked and hide such services. When checked it will show all services

**Comment by KurtStam** [comment]
People may want to integrate with those services too. They have APIs what can be published. I see no issue with treating them like any other service.

**Comment by jpechane** [comment]
But I think their exposure will be very rare. Another example would be an internal KeyCLoak instance - thus we propose just a kind of filter. To filter out a subset of services by default but still allow them to be exposed

**Comment by KurtStam** [comment]
I opened a Feature request: https://issues.jboss.org/browse/APIMAN-967.

**Comment by KurtStam** [comment]
Other minor enhancements to the apiman catalog: 
- fix link on download button on swagger ui
- adding filtering by namespace and labels

**Comment by KurtStam** [comment]
fixed
