### ISSUE TITLE
[apiman] KubernetesServiceCatalog.createServiceContract incrrectly handles unknown annotations

### ISSUE THREAD

**Issue by jpechane** [fabric8io/fabric8-ipaas#171]
See code https://github.com/fabric8io/fabric8-ipaas/blob/master/apiman/src/main/java/io/fabric8/apiman/KubernetesServiceCatalog.java#L190-L199
If *any* annotations are present the code supposes that all apiman annotations are present which can create an endpoint url like ``http://jws-app.jpechane.svc.cluster.local:8080/null``

**Comment by KurtStam** [comment]
Oops - added checking for null:
https://github.com/fabric8io/fabric8-ipaas/pull/176
