### ISSUE TITLE
[apiman] ApimanStarter should use logging instead of System.out

### ISSUE THREAD

**Issue by jpechane** [fabric8io/fabric8-ipaas#172]
At least method resolveServiceEndpoint is called from already started apiman so it should log the resolving information to logger for proper categorization

**Comment by KurtStam** [comment]
Good point.
Accidentally added the fix to an open PR, but these are the commit ids:
https://github.com/KurtStam/fabric8-ipaas/commit/6b6a7630c82e7b76bbcb1055cd830753949350f0
https://github.com/fabric8io/fabric8-ipaas/commit/a7543fe1d4c796a333ebdac71985923ac65be05d
