### ISSUE TITLE
[apiman] ApimanStarter.resolveServiceEndpoint sometimes resolves to pod IP instead of hostname

### ISSUE THREAD

**Issue by jpechane** [fabric8io/fabric8-ipaas#173]
Try importing elasticsearch-v1-masters service. It resolves into IP address of a pod instead of DNS name. So the log contains
```
Resolved host using DNS: 172.17.0.6
Defaulting elasticsearch-v1-masters port to: 9300
```
The other services are resolved properly to DNS names

**Comment by jimmidyson** [comment]
I assume this is because `elasticsearch-v1-masters` is actually a [headless service](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/services.md#headless-services), i.e. a service without an allocated IP address that is used mainly for discovering cluster seeds. Headless services resolve (A records) to pod IPs rather than service IPs as it does for non-headless services.

**Comment by KurtStam** [comment]
Do we need to do anything special on apiman's service import?

**Comment by jpechane** [comment]
From OpesShift documentation
> Service DNS can still be used and responds with multiple A records, one for each pod of the service, allowing the client to round-robin between each pod.
If it is the case we must not use the IP address as it is know because in this case gateway would send all requests to a single pod instance - which is wrong in case of scaling. So we still need to resolve to DNS name somehow and then for gateway to do resolution to multiple IPs and do round-robin on it - it might be done by Java automactically but it has to be verified.

**Comment by KurtStam** [comment]
Are you sure it is the Pod IP and not the Service IP? We are only using the nice DNS name so it's easier to read for humans. In this case DNS does not offer us a nice name, but the service IP should work just as well.

**Comment by KurtStam** [comment]
Let's not offer an automated import for headless services. The user can always import the endpoint manually if they really have a need for it.
