### ISSUE TITLE
[apiman] Only first 20 imported services are displayed in import catalog

### ISSUE THREAD

**Issue by jpechane** [fabric8io/fabric8-ipaas#178]
If I try to import catalog then the KubernetesServiceCatalog.search reaturns list of 30 AvailableApiBean instances but only 20 are displayed, no paging is available and filter filter only through those displayed.

**Comment by KurtStam** [comment]
@jpechane This is a apiman issue. Can you open a lira there to track it? I think it may already be on their radar, but I'm not sure for what version of apiman it is slated to get fixed.

**Comment by jpechane** [comment]
https://issues.jboss.org/browse/APIMAN-955

**Comment by KurtStam** [comment]
fixed
