### ISSUE TITLE
[apiman] endpoint address defaults to localhost for services outside of current namespace on OSE

### ISSUE THREAD

**Issue by dsimansk** [fabric8io/fabric8-ipaas#179]
APIMan deployed on OSE 3.1

When importing service that is outside of current APIMan namespace, it fails to resolve DNS and defaults to localhost. It should probably look for route associated with service and use `host` attribute. 

```
11:37:45,031  WARN Could not resolve DNS for sso-app, trying ENV settings next.
11:37:45,031  INFO Defaulting sso-app host to: localhost
11:37:45,031  INFO Defaulting sso-app port to: 8080
```

**Comment by dsimansk** [comment]
It's probably duplicate of #169.

**Comment by KurtStam** [comment]
At the moment, you need to deploy an apiman per namespace. So it is a bug that you can see services from other namespaces that will be fixed when https://github.com/fabric8io/fabric8-ipaas/pull/166
is merged in.
