### ISSUE TITLE
[apiman] Roles are hard-coded in BearerTokenFilter

### ISSUE THREAD

**Issue by jpechane** [fabric8io/fabric8-ipaas#180]
The code contains comment about linking roles to KeyCloak but it should also be based on OpenShift roles definition - for example link it to a project admin role.

**Comment by KurtStam** [comment]
Yeah, this needs further discussion, as there is no openshift api for 'get me the roles for this user'. I'd be in favor of using KeyCloak for all our SSO. I will report back if I have any news to report on this.

**Comment by jimmidyson** [comment]
On OpenShift you can't query what roles a user has but you can query "can <this user> do <this action>?". Is that useful?

**Comment by KurtStam** [comment]
We can use that as a workaround if we have to.

**Comment by KurtStam** [comment]
https://github.com/fabric8io/fabric8-ipaas/pull/212
