### ISSUE TITLE
Delete Organization when Deleting a project/namespace

### ISSUE THREAD

**Issue by KurtStam** [fabric8io/fabric8-ipaas#262]
When a project/namespace gets deleted, also cascade delete the organization on the apiman side. This depends on the Apiman REST API to support it:
https://issues.jboss.org/browse/APIMAN-890

**Comment by KurtStam** [comment]
If we don't delete the organization on the apiman side it lead to a security issue if someone re-uses the same namespace on the openshift side.

**Comment by msavy** [comment]
FYI - the above feature is on master

**Comment by KurtStam** [comment]
Yay will give it a spin!

**Comment by KurtStam** [comment]
The integration layer should also watch for delete service events and propagate those too
