### ISSUE TITLE
Is there an ENV Var available to change API Gateway URL

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-ipaas#307]
The API Gateway publishes the address of an endpoint using this path 

`http://apiman-gateway/gateway`

instead of 

`http://apiman-gateway.vagrant.f8/gateway/`

Is there an env var, ... that we could set to change it ?

**Comment by KurtStam** [comment]
I fixed a small bug there, but yes it defaults to the route i.e. 'https://apiman-gateway.vagrant.f8', and you can override it by setting a System param 'apiman.micro.gateway.public-endpoint' in the apiman-gateway.
