### ISSUE TITLE
Api endpoint different form the route

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-ipaas#308]
Apiman proposes as Api endpoint proposes this address for an Api

 `http://cdi-cxf.demo2.svc.cluster.local:80/cxfcdi ` 

instead of the address reported by the route

 `http://cdi-cxf-demo2.vagrant.f8/cxfcdi`

Questions : 
- How do you build the URL of the endpoint ?
- Ca we change the code to use instead the route published ? I can do that if you tell me where within the project ?

**Comment by KurtStam** [comment]
Yes the endpoint is defined as the backend service where it routes the request to. When you publish the service it a new 'endpoint' tab shows up in the apiman console and this should use the route info.
