### ISSUE TITLE
No Bearer Token is available for the Management Console

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-ipaas#362]
We can't open the apiman Management console as the Token is not available 

![screenshot 2016-06-10 11 25 32](https://cloud.githubusercontent.com/assets/463790/15960050/3c2420f6-2efe-11e6-9035-f174e6de5efc.png)

**Comment by KurtStam** [comment]
You will need a very recent console build for this to work. Can you inspect the link and paste the output for me?

**Comment by cmoulliard** [comment]
Which link ?

**Comment by KurtStam** [comment]
The link in the fabric8 console, that opens the apiman console.

**Comment by cmoulliard** [comment]
Here is the link that we get from the service view : `http://apiman.vagrant.f8/apimanui/api-manager/?q=`
which is not working for ssl access. The link will work using `https` protocol but the message about the bearer issue is still there.

Remark : I have reinstalled everything this morning : new Vagrant VM box, ...

**Comment by KurtStam** [comment]
Can you check if your console has this fix?
https://github.com/hawtio/hawtio-kubernetes/commit/fe56b26ae6b7ab335c8f8329880b36585d2ae451#diff-b06cfb9c8a5f42940fc42e9c0a7f2e5a

**Comment by cmoulliard** [comment]
I can't find it within this js file 

![screenshot 2016-06-13 18 05 21](https://cloud.githubusercontent.com/assets/463790/16014455/73367522-3191-11e6-9078-2aaa6a7ebfe4.png)

**Comment by KurtStam** [comment]
My fix will be in 2.1.242, but it's not yet released, so after that we will need to release the console.
https://github.com/hawtio/hawtio-kubernetes/tree/v2.1.241.

**Comment by KurtStam** [comment]
@cmoulliard This can be closed now that the new console is out right?

**Comment by cmoulliard** [comment]
yes
