### ISSUE TITLE
Import the plugins available

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-ipaas#365]
Since Apiman 1.2.4.Final, the list of the plugins available are displayed

![screenshot 2016-06-10 12 39 55](https://cloud.githubusercontent.com/assets/463790/15962013/7aa89c12-2f08-11e6-8f2e-0910c79c2b31.png)

but our configuration doesn't include them 

<img width="1357" alt="screenshot 2016-06-10 12 30 07" src="https://cloud.githubusercontent.com/assets/463790/15961840/68990116-2f07-11e6-8ff8-dfe54fa1d5db.png">

**Comment by KurtStam** [comment]
fixed
