### ISSUE TITLE
API registry supposed to be working ?

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-ipaas#95]
Before opening issues I wonder whether the ApiRegistry microservice is supposed to be working ? I ask because I get strange protocol errors which indicate that there has not been update recently here.

**Comment by davsclaus** [comment]
No I think its going to the sandbox, as apiman project itself is likely the place for api registry and governancen and all that for this.

@rajdavies @jstrachan is that correct I did I misunderstand something?

**Comment by KurtStam** [comment]
Correct Apiman now has a service catalog page to browse all services, at 
/apimanui/api-manager/catalog/api-catalog which looks like:
https://www.dropbox.com/s/ntcsg4ksb70jk0a/Screenshot%202016-01-13%2015.32.13.png?dl=0

**Comment by davsclaus** [comment]
Thanks @KurtStam - I think we should remove the old ApiRegistry then, @jstrachan any thoughts?

**Comment by KurtStam** [comment]
@jstrachan @rhuss I was thinking to make a pass over all the quickstarts now to add the official k8s Service Annotations (https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/service-discovery.md) for the WADL documents. That way all api documents should get reported in the Apiman Catalog, and it would fully replace the api-registry functionality. I can remove it after that, sound ok?

**Comment by davsclaus** [comment]
+1 from me

**Comment by rajdavies** [comment]
+1 from me too

**Comment by KurtStam** [comment]
Removing the api-registry and tracking the addition of the service annotations in the ipaas-quickstart project (https://github.com/fabric8io/ipaas-quickstarts/issues/1175)
